### ISSUE TITLE
Cuisines and Dishes

### ISSUE THREAD

**Issue by anupamme** [anupamme/cookup#1]
In the cuisine list: add a cuisine 'Other' - if none of the cuisine is what the user wants
In the dishes list: let the user add a manual dish and save it as it is in the db.

**Comment by snehalvpatil** [comment]
> In the cuisine list: add a cuisine 'Other' - if none of the cuisine is what the user wants
> In the dishes list: let the user add a manual dish and save it as it is in the db.

done
