### ISSUE TITLE
add privacy policy, TC, Cancellation &Refund Policy

### ISSUE THREAD

**Issue by anupamme** [anupamme/cookup#10]
For Privacy Policy use this: https://docs.google.com/document/d/1yqqWTE_jfC8F_u9UV9nLq3AUZR2wwpQGJigRJV3YQvg/pub

For Terms and Conditions use: https://docs.google.com/document/d/1bCwt0WccF7oDMBGAGRxtPgUfzqGzkUjtLnnE1JlL2dg/pub

For Refund use:
https://docs.google.com/document/d/1xYM1QHm9S5phnkzyENqJ3KXv37schlsiTp0Id_4IMwE/pub

For Company details use this:
Name: Pally Technologies Pvt Ltd
Address: BL-5, Shalimar Bagh (West), Delhi 110088
email: admin@cookupconnect.com

**Comment by anupamme** [comment]
In https://cookup.pally.in/privacy-policy:

Remove the following at the bottom:

[Re: Privacy Compliance Officer]

[622 Manglam Electronic Market Jaipur Rajasthan India 302001]

In https://cookup.pally.in/terms-conditions

operated byPally Technologies (insert space between by and Pally)

For refunds (https://cookup.pally.in/refund-policy), use the following document:

https://docs.google.com/document/d/1ct8Bz0j_MjIQooUtS3gr4Q-V6hiJkY2L7Op-bbwxhXg/edit?usp=sharing

**Comment by snehalvpatil** [comment]
changes done
