### ISSUE TITLE
Issues in edit class details

### ISSUE THREAD

**Issue by anupamme** [anupamme/cookup#3]
1. Ingredient url disappears
2. Image also disappears.
3. There may be other items which are disappearing in edit class flow. So check them as well.

**Comment by anupamme** [comment]
There is more:

https://cookup.pally.in/class-created

Class details are hard coded e.g. date, price.

**Comment by snehalvpatil** [comment]
> 1. Ingredient url disappears
> 2. Image also disappears.
> 3. There may be other items which are disappearing in edit class flow. So check them as well.

all resolved, the only manual list is pending because we are getting issue from backend

**Comment by snehalvpatil** [comment]
> There is more:
> 
> https://cookup.pally.in/class-created
> 
> Class details are hard coded e.g. date, price.

solved
