### ISSUE TITLE
class setting - time and duration details

### ISSUE THREAD

**Issue by anupamme** [anupamme/cookup#45]
![class_flow_duration](https://user-images.githubusercontent.com/667857/140013507-0aa7849e-b690-4ed6-bd49-78c845f0b522.png)
![class_flow_time](https://user-images.githubusercontent.com/667857/140013510-ec4e4864-5652-4232-bf55-3efef96c9229.png)

24 hr time option
Units like minutes/hour to be shown for duration field (show the metrics in duration e.g. hrs/mins, otherwise it is a bit confusing)

**Comment by snehalvpatil** [comment]
changes done

**Comment by anupamme** [comment]
closing this.
