### ISSUE TITLE
order of classes (https://cookup.pally.in/my-classes)

### ISSUE THREAD

**Issue by anupamme** [anupamme/cookup#47]
change the order to 

upcoming, past, active

**Comment by anupamme** [comment]
change the copy:  

Change the copy to “add another cuisine” instead of add other dish.

**Comment by anupamme** [comment]
merge active and upcoming tabs into upcoming.

**Comment by shubhamch20** [comment]
Fixed

**Comment by anupamme** [comment]
closing it.
