### ISSUE TITLE
my classes

### ISSUE THREAD

**Issue by anupamme** [anupamme/cookup#5]
https://cookup.pally.in/my-classes

Currently, the active class is a dummy class - remove it.
Why do we need the Active class tab, we just need upcoming and past classes. In the upcoming list, the ongoing class can me marked to indicate that it is ongoing.

**Comment by snehalvpatil** [comment]
active class tab removed

**Comment by anupamme** [comment]
what is: View Recommended Class

Is this per design? If yes, let it be otherwise remove it.
