### ISSUE TITLE
learners flow - template copy

### ISSUE THREAD

**Issue by anupamme** [anupamme/cookup#51]
See the copy - it is template. where is it coming from? There is no such input in the teacher's flow. Ask the design team if needed.

<img width="1440" alt="Screenshot 2021-12-17 at 20 42 52" src="https://user-images.githubusercontent.com/667857/146668834-1bdd5d79-68ed-4b24-9392-26f9c151a044.png">

**Comment by anupamme** [comment]
https://cookup.pally.in/classdetails/27

still contains lorem ipsum.

**Comment by shubhamch20** [comment]
> https://cookup.pally.in/classdetails/27
> 
> still contains lorem ipsum.

Fixed

**Comment by anupamme** [comment]
This is fixed.
